# Generated by Django 6.0.6 on 2026-08-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_alter_complaint_options_alter_complaint_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
    ]
