# Generated by Django 6.0.6 on 2026-09-05
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0007_payment_payment_method_payment_qr_duplicate_warning_and_more",
        ),
        ("returns", "0005_complaintmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaintmessage",
            name="sender_user",
        ),

        migrations.RemoveField(
            model_name="complaintmessage",
            name="sender",
        ),

        migrations.AddField(
            model_name="complaintmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaint_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AlterField(
            model_name="complaint",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who resolved the complaint.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AlterField(
            model_name="complaint",
            name="response",
            field=models.TextField(
                blank=True,
                help_text="Legacy admin response to the customer.",
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="complaintmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),

        migrations.AlterField(
            model_name="return",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-filled from the linked order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="returns",
                to="orders.customer",
            ),
        ),

        migrations.AlterField(
            model_name="return",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time the return was approved, rejected, or completed.",
                null=True,
            ),
        ),
    ]