# Generated by Django 6.0.6 on 2026-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_sent_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, help_text='ID of the referenced entity (order_number, return_id, complaint_id)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('return', 'Return'), ('complaint', 'Complaint')], help_text='Type of entity this notification references: order, return, or complaint', max_length=20, null=True),
        ),
    ]
