# Generated by Django 6.0.6 on 2026-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('return', 'Return'), ('complaint', 'Complaint')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_via',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web', 'Web')], default='web', max_length=20),
        ),
    ]
