# Generated by Django 6.0.6 on 2026-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('return', 'Return'), ('complaint', 'Complaint'), ('product', 'Product')], max_length=20, null=True),
        ),
    ]
