# Generated by Django 6.0.6 on 2026-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_via',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web', 'Web'), ('in_app', 'In-App')], default='web', max_length=20),
        ),
    ]
