# Generated by Django 6.0.6 on 2026-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
    ]
