# Generated by Django 6.0.6 on 2026-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
