# Generated by Django 6.0.6 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_verified_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_phone', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_change_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_change_requests',
            },
        ),
    ]