# Generated by Django 6.0.6 on 2026-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('qr', 'QR')], default='stripe', help_text='Payment method used: stripe or qr', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_duplicate_warning',
            field=models.BooleanField(default=False, help_text='Set to True if duplicate proof detected'),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_image_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of screenshot for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_reject_reason',
            field=models.TextField(blank=True, help_text='Reason given when admin rejects QR proof', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_screenshot_url',
            field=models.TextField(blank=True, help_text='URL of uploaded QR payment screenshot', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When proof was uploaded (moves to under_review)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID provided by customer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], help_text='manual for QR orders, automatic for Stripe orders', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_transaction_reference',
            field=models.CharField(blank=True, help_text='Required when refund_method is manual', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
