# Generated by Django 6.0.6 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_fix_customer_blank_phone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('order_placed', 'Order Placed'),
                    ('pending_payment', 'Pending Payment'),
                    ('on_hold', 'On Hold'),
                    ('confirmed', 'Confirmed'),
                    ('shipped', 'Shipped'),
                    ('out_for_delivery', 'Out for Delivery'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending_payment',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('pending', 'Pending'),
                    ('under_review', 'Under Review'),
                    ('paid', 'Paid'),
                    ('rejected', 'Rejected'),
                    ('refunded', 'Refunded'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_upload_deadline',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Deadline to upload QR proof before auto-cancel (order_placed stage only)',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_extension_used',
            field=models.BooleanField(
                default=False,
                help_text='Whether the one-time +5 minute upload extension has already been used',
            ),
        ),
    ]