# Generated by Django 6.0.6 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_placed_status_qr_upload_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clear_cart_on_qr_proof',
            field=models.BooleanField(default=False),
        ),
    ]