# Generated by Django 6.0.6 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_clear_cart_on_qr_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('order_placed', 'Order Placed'),
                        ('pending_payment', 'Pending Payment'),
                        ('on_hold', 'On Hold'),
                        ('confirmed', 'Confirmed'),
                        ('shipped', 'Shipped'),
                        ('out_for_delivery', 'Out for Delivery'),
                        ('delivered', 'Delivered'),
                        ('cancelled', 'Cancelled'),
                    ],
                    max_length=20,
                )),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['changed_at'],
            },
        ),
    ]