# Generated by Django 6.0.6 on 2026-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_chatsession_deleted_at_chatsession_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
