# Generated by Django 6.0.6 on 2026-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_chatupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=4, null=True),
        ),
    ]
