# Generated by Django 6.0.6 on 2026-09-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_migrate_owner_to_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
