# Generated by Django 6.0.6 on 2026-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
