# Generated by Django 6.0.6 on 2026-08-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_discount_is_delete_product_is_delete'),
        ('products', '0009_discount_is_delete'),
    ]

    operations = [
    ]
