# Generated by Django 6.0.6 on 2026-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_merge_20260825_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock'), ('damaged', 'Damaged'), ('correction', 'Correction'), ('return', 'Return'), ('other', 'Other'), ('order_placed', 'Order Placed (checkout)'), ('order_cancelled', 'Order Cancelled (stock restored)'), ('order_confirmed', 'Order Payment Confirmed (stock deducted)')], max_length=30),
        ),
    ]
