# Generated by Django 6.0.6 on 2026-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock reserved for pending payment orders'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='Total physical stock available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Use total_stock instead'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock'), ('damaged', 'Damaged'), ('correction', 'Correction'), ('return', 'Return'), ('other', 'Other'), ('order_placed', 'Order Placed (reserved)'), ('order_cancelled', 'Order Cancelled (released)'), ('order_confirmed', 'Order Payment Confirmed (deducted)'), ('qr_approved', 'QR Payment Approved'), ('qr_rejected', 'QR Payment Rejected'), ('qr_timeout', 'QR Payment Timeout'), ('stripe_timeout', 'Stripe Payment Timeout')], max_length=30),
        ),
    ]
