# Generated by Django 6.0.6 on 2026-09-28 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_review_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Optional — reviewer's profile picture, shown next to their review.", max_length=255, null=True, verbose_name='image'),
        ),
    ]
